

export const CATEGORIES = [
    "JavaScript",
    "React",
    "Node.js",
    "TypeScript",
    "CSS",
    "HTML",
    "System Design",
    "Data Structures",
    "Algorithms",
    "Database",
    "Frontend",
    "Backend",
    "Full Stack",
    "DevOps",
    "Testing",
    "Design Patterns",
    "Web Development",
    "Mobile Development",
    "Game Development",
    "AI",
    "Machine Learning",
    "Cybersecurity",
    "Security",
    "UX Design",
    "UI/UX Design",
    "Project Management",
    "Project Management",
]